### ISSUE TITLE
1.2.1 with new3ds has bug

### ISSUE THREAD

**Issue by Matthewliu7** [CrimsonMaple/Rei-Six#6]
new3ds b9 1.3
when boot rei1.2.1
powerlight off after splash

but my friends's old3ds no problem

**Comment by CrimsonMaple** [comment]
Update 3ds before updating rei-six

**Comment by Matthewliu7** [comment]
I‘m 11.8.0-41J....

**Comment by CrimsonMaple** [comment]
Is there a file on your SD card in the "/rei" folder called "debug.log"? If so open that up using any text editor and tell me what it says

**Comment by Matthewliu7** [comment]
Failed to decrypt arm9 binary...

**Comment by thetruecatboy** [comment]
How did you update your system?

**Comment by Matthewliu7** [comment]
I think I found the cause...
I'm update online...
but before normal update,I make GW11.6MOD system update,and it won't be replaced 11.8update..
gw cakes and luma is normal so I'm forget it.....o(╥﹏╥)o

**Comment by CrimsonMaple** [comment]
Okay so something might be wrong with your secret sector. try running this build and telling me if the error code is different. https://www.dropbox.com/s/91jqzn0idsniasp/boot.firm?dl=0
Be sure to delete the old log file before running this build.

**Comment by thetruecatboy** [comment]
If you are running a Frankenfirm for Gateway, then that's your issue. You need to be running a clean NAND for the paths to work properly with Rei-Six

**Comment by Matthewliu7** [comment]
Key1/2 mismatch...arm9 binary... 
I think it's that problem...So don't mind...

**Comment by CrimsonMaple** [comment]
Well the fact that it booted this far means your native firm is the most recent. So it's not that. It's that your secretSector is messed up. I can whip up a quick binary to fix this but you need to find the secret_sector.bin yourself.

**Comment by Matthewliu7** [comment]
How can I find it?
i just find sector0x96.bin in godmode9-sysnand virtual,about 512Byte

**Comment by CrimsonMaple** [comment]
download the secret_sector.bin contained in a torrent link here: https://3ds.hacks.guide/a9lh-to-b9s
and then rename it to sector0x96.bin and replace that file in sysnand virtual with the new one. Or just use this and follow the Readme. https://www.dropbox.com/s/0umdpk57ej9u95c/secretSector_fix.zip?dl=0

**Comment by Matthewliu7** [comment]
It's worked!
now gw cakes luma and rei-six all boot normal!
thanks!
