### ISSUE TITLE
Any way to access the homebrew launcher?

### ISSUE THREAD

**Issue by skirlez** [CrimsonMaple/Rei-Six#9]
Yes, I know the CFW is discontinued. And I am aware I'll probably get zero replays.
How do I access the homebrew launcher with this CFW?
I've tried both the homebrew launcher wrapper:
https://github.com/mariohackandglitch/homebrew_launcher_dummy/releases/tag/v1.0
and the older hblauncher loader:
https://github.com/yellows8/hblauncher_loader/releases
and both do not work no matter what I try!
The launcher wrapper says I have to reconfigure Luma (Can't do that)
The hblauncher loader says it can't download a payload.
So I'm lost. Is there any way to access the homebrew launcher or heck even boot 3dsx files?
I've even tried creating a fowarder manually. doesn't work.

**Comment by skirlez** [comment]
I got it to boot using this:
https://gbatemp.net/threads/cxitool-convert-3dsx-to-cia-directly.440385/
but I can't launch games.

**Comment by Multimegamander** [comment]
this is late, but that's user error, use the old way of launching the hbl

**Comment by skirlez** [comment]
Yeah, I tried the old way, but no one knows how to use it or documented it. I found a solution thanks to a member on GBAtemp.
It is never documented in hblauncher loader, but in order to get it to work, all you need is to name the otherapp payload to the exact version number.
